trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    echo "Upgrading pip..."
    python -m pip install --upgrade pip
  displayName: 'Upgrade pip'

- script: |
    echo "Installing dependencies..."
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    echo "Running basic Python test..."
    python --version
    python -c "print('Hello from Azure Pipeline test!')"
  displayName: 'Basic Python Test'

- script: |
    echo "Checking if app.py exists..."
    if [ -f "app.py" ]; then
      echo "app.py found!"
    else
      echo "app.py not found!"
      exit 1
    fi
  displayName: 'Check for app.py'

- script: |
    echo "Running basic unit test..."
    pytest -v
  displayName: 'Run unit tests with pytest'

- script: |
    echo "Running app.py..."
    python app.py
  displayName: 'Run app.py'
