# Starter pipeline for a Music Player Batch Creator
# This pipeline will test, package, and potentially deploy your batch script.
# Add steps that build, run tests, deploy, and more.

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Step 1: Echo a hello message
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Step 2: Echo a multi-line message
- script: |
    echo Add other tasks to build, test, and deploy your Music Player Batch Script.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Step 3: Check if the batch file exists in the repository
- script: |
    if exist ./music_player.bat (
        echo Batch file exists!
    ) else (
        echo Batch file not found!
        exit /b 1
    )
  displayName: 'Check if batch file exists'

# Step 4: Test the batch file by running it in a Windows environment (using a Windows container)
# This step simulates running the batch file in a Windows environment.
- task: UseWindowsContainer@0
  inputs:
    containerImage: 'mcr.microsoft.com/windows/servercore:ltsc2019'
  displayName: 'Test Batch Script in Windows Container'
  script: |
    copy ./music_player.bat C:\music_player.bat
    C:\music_player.bat
    echo Test complete.
    
# Step 5: Package the batch file (example of creating a .zip file)
- script: |
    echo Packaging batch script...
    zip -r music_player.zip ./music_player.bat
  displayName: 'Package Music Player Batch Script'

# Step 6: Optional deployment step (you can modify this based on your deployment target)
# For example, upload the zip file to a storage location or deploy it to a server.
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'music_player.zip'
    ArtifactName: 'drop'
  displayName: 'Publish Artifacts'

# Step 7: Optional - Deploy the zip file to a specific location (e.g., web server or cloud storage)
- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/music_player.zip'
    azureSubscription: '<Your-Azure-Subscription>'
    Destination: 'AzureBlob'
    StorageAccountName: '<Your-Storage-Account>'
    ContainerName: '<Your-Blob-Container>'
    BlobPrefix: 'music-player-deployment/'
  displayName: 'Deploy Music Player Batch Script'
