trigger:
  - main  # Trigger pipeline when changes are pushed to the main branch

pool:
  vmImage: ubuntu-latest  # Use a hosted Ubuntu agent

steps:
# Step 1: Checkout the code from GitHub
- checkout: self

# Step 2: Set up Python environment
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Use the latest Python 3.x version
  displayName: "Set up Python"

# Step 3: Install dependencies from the correct path
- script: |
    python -m pip install --upgrade pip
    pip install -r project/requirements.txt  # Adjusted path to requirements.txt
  displayName: "Install dependencies"

# Step 4: Run unit tests using pytest
- script: |
    python -m pytest tests/  # Assuming tests are located in a 'tests' directory
  displayName: "Run tests"

# Step 5: Run the app.py script
- script: |
    python app.py
  displayName: "Run app.py"
