trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Set up Python'

- script: |
    python -m pip install --upgrade pip
    pip install -r project/requirements.txt
  displayName: 'Install Dependencies'

- script: |
    echo "Hello from Music Playlist Batch Creator!"
  displayName: 'Run Hello Script'

- script: |
    python performance_test.py
  displayName: 'Performance Test'

- script: |
    python -m unittest discover -s project/tests -p "test_*.py"
  displayName: 'Run Unit Tests'

- script: |
    pip install flake8
    flake8 project/
  displayName: 'Code Style Check'
