trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  pythonVersion: '3.10'

steps:

# Step 1: Use Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    addToPath: true

# Step 2: Install pip and dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pip install gdown
  displayName: 'Install Python Dependencies'

# Step 3: Download music_df.pkl from Google Drive using gdown
- script: |
    mkdir -p data
    gdown --id 1e8CtNMNCGfcFKiH4amW3NyliIn5Cf4P3 -O data/music_df.pkl
  displayName: 'Download music_df.pkl from Google Drive'

# Step 4: Sanity check to test imports
- script: |
    echo "Sanity check: testing imports..."
    python -c "import flask, pandas, numpy, spotipy, pymongo, werkzeug, pickle, difflib; print('✅ All imports successful!')"
  displayName: 'Sanity Check - Python Imports'
